# repo_url: https://github.com/northshorewc/ccr2016
remote_branch: gh-pages
site_url: https://northshorewc.github.io/ccr2016
site_author: Eric Kiefer
site_name: 2016 Annual Water Quality Report
theme: readthedocs
theme_dir: readthedocs-theme
extra_javascript: 
  # - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full
  - https://use.fontawesome.com/ccef82ad40.js
markdown_extensions:
  - admonition:
  - def_list:
  - footnotes: 
  - toc:
  - mdx_math:
  # - pymdownx.arithmatex:
pages:
  - Home: index.md