repo_url: https://github.com/EKiefer/training
remote_branch: gh-pages
site_url: https://ekiefer.github.io/training
site_author: Eric Kiefer
site_name: NSWC Training
theme: material
theme_dir: theme
extra_javascript: 
  # - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full
markdown_extensions:
  - admonition:
  - toc:
  - mdx_math:
  # - pymdownx.arithmatex:
pages:
  - Home: index.md
  - Modules: modules.md
  - General Concepts: 
    - Operator Math: general_concepts/operator_math.md
    - Operator Chemistry : general_concepts/operator_chemistry.md
  - About: about.md