repo_url: https://github.com/northshorewc/ccr2016
remote_branch: gh-pages
site_url: https://northshorewc.github.io/ccr2016
site_author: Eric Kiefer
site_name: 2016 Annual Water Quality Report
theme: material
theme_dir: theme
extra_javascript: 
  # - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full
markdown_extensions:
  - admonition:
  - toc:
  - mdx_math:
  # - pymdownx.arithmatex:
pages:
  - Home: index.md